services:
  - type: web
    name: neargram
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: python server.py
    healthCheckPath: /
    autoDeploy: true
    pythonVersion: 3.12.4
