services:
  - type: web
    name: neargram
    runtime: python
    plan: free
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: python server.py
    healthCheckPath: /
    autoDeploy: true
    pythonVersion: 3.12.4
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: neargram-db
          property: internalConnectionString
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: SEED_BOTS
        value: "1"
      - key: SEED_BOTS_COUNT
        value: "120"
      - key: BOT_PASSWORD
        value: "botpass"

databases:
  - name: neargram-db
    plan: free
    databaseName: neargram
    user: neargram